[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
strip = true

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"

[workspace.dependencies]
walkdir = "2.3.2"
pallas = { git = "https://github.com/txpipe/pallas", rev = "7cb1ffe100befaa6236f14c14081961c44d6ad21" }
insta = { version = "1.30.0", features = ["yaml", "json"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
